language: node_js
node_js:
  - "8"
script:
  - yarn run build
before_install:
  - openssl aes-256-cbc -K $encrypted_35cfa241f843_key -iv $encrypted_35cfa241f843_iv -in publish-key.enc -out ~/.ssh/publish-key -d
  - chmod u=rw,og= ~/.ssh/publish-key
  - echo "Host github.com" >> ~/.ssh/config
  - echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "''"
  local_dir: dist
  target_branch: gh-pages
  on:
    branch: master